spring:
  application:
    name: agendamento-baixa-boleto
  cloud:
    aws:
      region:
        static: sa-east-1

server:
  port: 8080

app:
  sqs:
    agendamento-cancelamento-queue-url: ${SQS_AGENDAMENTO_CANCELAMENTO_URL}
